/* Generated by Nim Compiler v0.16.1 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -g  -I/Users/zachcarter/projects/Nim/lib -o /Users/zachcarter/projects/nuklear-nim/nimcache/stdlib_parseutils.o /Users/zachcarter/projects/nuklear-nim/nimcache/stdlib_parseutils.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef linux

#line 310 "/Users/zachcarter/projects/Nim/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s0);
#line 305 "/Users/zachcarter/projects/Nim/lib/system/excpt.nim"
N_NOINLINE(void, stackoverflow_II46IjNZztN9bmbxUD8dt8g)(void);
#line 50 "/Users/zachcarter/projects/Nim/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void);extern TFrame* frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;


#line 310 "/Users/zachcarter/projects/Nim/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
#line 311 "/Users/zachcarter/projects/Nim/lib/system/excpt.nim"
	LOC1 = (NI)0;
#line 311 "/Users/zachcarter/projects/Nim/lib/system/excpt.nim"
	{
#line 311 "/Users/zachcarter/projects/Nim/lib/system/excpt.nim"
		if (!(frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);	}
	goto LA2;
	LA4: ;
	{
#line 311 "/Users/zachcarter/projects/Nim/lib/system/excpt.nim"
		LOC1 = ((NI) ((NI16)((*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
#line 312 "/Users/zachcarter/projects/Nim/lib/system/excpt.nim"
	(*s0).prev = frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
#line 313 "/Users/zachcarter/projects/Nim/lib/system/excpt.nim"
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = s0;
#line 314 "/Users/zachcarter/projects/Nim/lib/system/excpt.nim"
	{
#line 314 "/Users/zachcarter/projects/Nim/lib/system/excpt.nim"
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;

#line 314 "/Users/zachcarter/projects/Nim/lib/system/excpt.nim"
		stackoverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9: ;
}


#line 50 "/Users/zachcarter/projects/Nim/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {

#line 51 "/Users/zachcarter/projects/Nim/lib/system/excpt.nim"
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;}
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void) {
	nimfr("parseutils", "parseutils.nim")
	popFrame();}

NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void) {
}

